### ISSUE TITLE
One Player Stuck In An Infinite Loop

### ISSUE THREAD

**Issue by RedBreloom** [Modding-Legacy/Aether-Legacy#378] opened 2019-02-09 18:27 UTC
**Aether Legacy Version(s) Affected**:
1.12.2 V 1.4.0

**Forge version**: 
forge-1.12.2-14.23.5.2811

**Extra Mods**: 
Animania
Biomes O Plenty
JEI
IVToolkit
Recurrent Complex
CraftStudio API
Decocraft 2
Pam's Harvestcraft
Ferdinand's Flowers
PTRLib
**Issue:**
One of my players makes a portal to the Aether and are then caught in an infinite spawn loop between the overworld and the aether. They can't move to escape it so they just stuck in a loop of loading and unloading in the world. The other players did not experience this.

**How to reproduce:**
Not sure, the player tired to move their portal but it was either too close to the 'broken' portal or it doesn't matter in the first place. We are not sure why this is happening to only them. When they got a timeout kick/shutdown minecraft they rejoined at (axis) Y10 underneath their animal pen near their house but not under their portal. They were in creative so they didn't die but yeah. They then tried to move the portal a bit (but i'm not sure how far), and the same results happened to them.  I'm thinking the Aeither portal may be glitched for them alone somehow?

**Crash log:**
No crash other than a timeout on their end, the console just showed them continually loading and unloading the overworld and the aether.

**Comment by KingPhygieBoo** [comment] 2019-03-31 12:39
Dupe of #279

**Closed by KingPhygieBoo** 2019-03-31 12:39 UTC
Labels: Forge
