### ISSUE TITLE
[Bug] getting killed just once no makes you unable to play the game at all

### ISSUE THREAD

**Issue by SirAron111** [Modding-Legacy/Aether-Legacy#371] opened 2019-02-01 15:33 UTC
**Aether Legacy Version(s)**
_Please make sure you are using the latest version for whatever Minecraft version you are using_

**Minecraft Version(s) Affected:**
1.12.2
**Extra Mod(s):**
Trying to Update my modpack DImension Zero with new version of Aether

**Describe the bug**
So I updated the version to the newest as of this date for 1.12.2
I was testing around with it locking for bugs like I always do before pushing new mod versions to my main pack updates.
I died and suddenly on respawn I can’t break any more blocks, randomly spaz out, can sometimes see myself standing next to my spawn and randomly take dmg from noting until I die again and again and again and even when I am already in respawn screen I take dmg and die apparently.
I narrowed it down to the new aethe mod version probably a bug with another mod in the pack but this only happens with the new Aether Legacy 1.12.2-v1.4.0 version the previous one worked fine.

**Expected behavior**
Being able to normally die respawn and go on like always

**Logs/Crash Logs and Screenshots**
https://pastebin.com/WbJ64K5R not a crash log since it doesn’t crash it just bugs out in game so here is the game log

**Additional context**
Reproducable 100%
1.	Download Dimension Zero Modpack
2.	Manually update delete the any older aether legacy version and add the new one (Aether Legacy 1.12.2-v1.4.0) to the mods folder.
3.	Spawn in the world attack any hostile mob or just drawn yourself whatever just die in one way or another.
4.	Once you respawn you will spaze out / be unable to break blocks and randomly die over and over again from nothing.

**Comment by 115kino** [comment] 2019-02-26 00:35
We updated our API for v1.4.0. The Tombstone mod is the cause for this crash and was fixed in their latest version. Please update your version of [Tombstone](https://minecraft.curseforge.com/projects/corail-tombstone/files/2675535)

**Closed by 115kino** 2019-02-26 00:35 UTC
