### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by Snez0K** [Modding-Legacy/Aether-Legacy#322] opened 2018-07-06 10:37 UTC
PLEASE FILL OUT EVERYTHING! 
Make sure that you are:
+++aether_legacy-1.12.2-v3.0.jar+++ running the latest version of Aether Legacy. In some cases, you may be having an issue of an old bug we've fixed a long time ago.

+++forge-1.12.2-14.23.4.2705-universal.jar on server / client+++ Also make sure you are running the latest or recommended version of Forge.

+++Here my modlist: https://imgur.com/a/Rpe1jn4 +++ If you are running extra mods, please list which mods you are running along with Aether Legacy or list the modpack you are running. 

+++ will send 2 crashreports from 2 PC's+++Lastly, please provide a crash log if you have one.

**Aether Legacy Version(s) Affected**: aether_legacy-1.12.2-v3.0.jar

**Forge version**: forge-1.12.2-14.23.4.2705-universal.jar

**Extra Mods**: Here my modlist: https://imgur.com/a/Rpe1jn4

**Issue:**: Client Crash

**How to reproduce:** Really didn't know, try to see logs. 

**Crash log:**
[crash-2018-07-06_13_07_44-client (1).txt](https://github.com/Modding-Legacy/Aether-Legacy/files/2170104/crash-2018-07-06_13_07_44-client.1.txt)
[crash-2018-07-06_14_51_39-client (1).txt](https://github.com/Modding-Legacy/Aether-Legacy/files/2170105/crash-2018-07-06_14_51_39-client.1.txt)

**Comment by KingPhygieBoo** [comment] 2018-07-08 05:29
Dupe of #311

**Closed by KingPhygieBoo** 2018-07-08 05:29 UTC
