### ISSUE TITLE
Duel Wielding Option From Battle Gear 2 Doesn’t Work With Aether Legacy 1.7.10

### ISSUE THREAD

**Issue by Xooke** [Modding-Legacy/Aether-Legacy#363] opened 2018-12-13 05:11 UTC
**Aether Legacy Version(s) Affected**:
1.7.10
**Forge version**: 
1.7.10
**Extra Mods**: 
BattleGear 2
TooManyItems
MoCreatures
**Issue:**
When the Aether Mod and Battle Gear are running at the same time, the duel wielding option that the Batfle Gear Mod offers doesn’t work (Only shows one hand)
**How to reproduce:**
Run Battle Gear 2 and the Aether Mod at the same time and only the right hand will appear when you attempt to duel wield (Press R on the keyboard)
**Crash log:**
There was no crash so i assume this isn’t needed

Without Aether Mod
![4c42464c-674d-4a1c-9f6e-51b14e77b7c7](https://user-images.githubusercontent.com/45839691/49917031-7a343e00-fe6b-11e8-9f30-bd4dc136d05e.png)

With Aether Mod
![335d0b99-c6f0-4353-baf8-b1c2eec90aab](https://user-images.githubusercontent.com/45839691/49917043-8cae7780-fe6b-11e8-92eb-070d599de8b0.png)

**Comment by Arokana** [comment] 2018-12-18 03:05
I'm currently having this issue as well. The issue is annoying, but hopefully it gets fixed soon.

**Comment by 115kino** [comment] 2018-12-30 07:48
This issue is now fixed in v1.0.1 for Aether Legacy 1.7.10. You can download the latest version [here](https://minecraft.curseforge.com/projects/aether-legacy/files)

**Closed by 115kino** 2018-12-30 07:48 UTC
