### ISSUE TITLE
Aether Portal Infinity Loop

### ISSUE THREAD

**Issue by Boolyman** [Modding-Legacy/Aether-Legacy#87] opened 2017-03-02 03:33 UTC
I have, on more than one occassion, gotten stuck in an endless loop of teleporting to and from the Aether.  I dont even have time to step out of the portal before the loading screen starts sending be mack.  Even holding the walk button forward nonstop in an attempt to run out of the portal as soon as possible, doesnt work.  I almost had to restart my world after getting stuck in a teleporting loop for an hour just now.  I only got out of it by finally being able to spam punch to break a block in the portal as I came through.

PLEASE put at least a 5 second cooldown on your portal teleports.

**Comment by 115kino** [comment] 2017-03-02 04:24
Duplicate of #28 (Fixed in v1.4)

**Closed by 115kino** 2017-03-02 04:24 UTC
