### ISSUE TITLE
Zanite armor protection bug

### ISSUE THREAD

**Issue by EdgyWedgy** [Modding-Legacy/Aether-Legacy#221] opened 2017-11-11 11:06 UTC
When I put zanite armor on, the protection bar displays it incorrectly. it really makes the zanite a lot weaker.

**Comment by ItzDennisz** [comment] 2017-11-11 15:35
Duplicate of https://github.com/Modding-Legacy/Aether-Legacy/issues/186

**Closed** 2017-11-11 15:39 UTC
