### ISSUE TITLE
[1.10.2][Bug] Main Menu issues

### ISSUE THREAD

**Issue by MysticAura** [Modding-Legacy/Aether-Legacy#104] opened 2017-03-24 00:40 UTC
MC: 1.10.2
Forge: 2254
Mod Version: 1.4

Disabling the main menu in configs has no effect. Main menu also doesn't remember the settings you change (World and Theme buttons)

**Comment by TheCorruption** [comment] 2017-03-24 02:03
Dupe of #94

**Closed** 2017-03-27 20:55 UTC
