### ISSUE TITLE
Creative portal use causes infinite loop.

### ISSUE THREAD

**Issue by Claycorp** [Modding-Legacy/Aether-Legacy#137] opened 2017-06-16 16:54 UTC
If you enter a portal in creative you are stuck telepoting between two dimensions. You need to make the portals work like nether portals so when you use it it can't act again until you leave it and re-enter.

**Comment by 115kino** [comment] 2017-06-19 18:05
duplicate of #128

**Closed by 115kino** 2017-06-19 18:05 UTC
