### ISSUE TITLE
The Sun Spirit Is A Liar!

### ISSUE THREAD

**Issue by UnlimatedStone9** [Modding-Legacy/Aether-Legacy#328] opened 2018-07-27 19:19 UTC
The Sun Spirit has one famous quote, "I am the sun spirit, embodiment of the Aether's eternal daylight as long as I am alive the sun will never set on this world"

The thing that makes him a liar is the fact that when I went to fight him it was literally night, clearly he has no power over the daylight and that's an issue

**Comment by ItzDennisz** [comment] 2018-07-27 19:38
this is a duplicate of a duplicate of a duplicate of possibly even more duplicates. it'd be great if people checked already existing issues before submitting their own.

**Closed** 2018-07-27 19:39 UTC
