### ISSUE TITLE
Annoying portal bug

### ISSUE THREAD

**Issue by NoahJelen** [Modding-Legacy/Aether-Legacy#316] opened 2018-06-22 17:33 UTC
Aether Legacy Version(s) Affected: 2.0 (for MC 1.12.2)
Forge version: 14.23.4.2708 (for MC 1.12.2)
Extra Mods: 
Galacticraft
Foamfix
Quark
Block Armor
Extra Rails
Waila
Iron Chests
JEI
More Planets (Galacticraft addon)
More Furnaces
Nether Noah Paradise Mod (I made this one)
Redstone Paste
WorldEdit
Xaero's Minimap
Xaero's Worldmap
Issue:When I go through an aether portal, it teleports me to the Aether, and the back to the overworld. This will happen repeatedly really fast, giving me no time to leave the portal and making have to kill java.
How to reproduce:Go through an Aether Portal

**Comment by NoahJelen** [comment] 2018-06-22 17:37
PS: This only happens in creative mode

**Comment by EnderT5** [comment] 2018-07-05 16:30
It happens in server too. Going inside Aether isn't a problem but if you are playing on a server and you go inside Aether portal to go back to the overworld, you stuck inside portal and teleport between overworld and Aether very fast and start getting damaged. If you die inside the portal while you are stuck inside portal, you lost your items. I'm using Aether Legacy 3.0 (1.12.2)

**Comment by KingPhygieBoo** [comment] 2018-07-08 05:22
This issue seems to only happen on low end hardware, I cannot reproduce this myself.

**Comment by EnderT5** [comment] 2018-08-04 06:41
I have GTX 1050 Ti, i7 7700HQ and 32 GB DDR4 RAM. I have a good system. My problem happens when playing in a server and in survival mode. This bug causes death and lose of the all items.

**Comment by jotac0** [comment] 2018-08-10 09:36
to me it also happens, but only once in a while, single player.
i have a NVidea Geforce 930m.

**Comment by DemonfangArun** [comment] 2018-10-18 01:33
I can confirm this is a thing. For me it happens on first teleport. It's probably related to the fact that the Aether is mostly empty and loads really fast, without giving you time to move from the portal before it's done loading. As noted above, only happens in creative. It might be worth adding some sort of delay for creative mode to give a couple seconds to move from the portal, or add a key modifier for creative like aroma1997's mining world portal.

**Comment by BabblingFishes** [comment] 2018-10-29 17:03
i7 4700HQ, NVIDIA GTX 860M, 16GB RAM

I'm running a server on one core and playing on another, and I get this issue only in creative mode. From the client end, there appears to be no cooldown whatsoever on the portal trigger. From the server end, there appears to be 1-4 seconds between loading and unloading the world. No error messages.

With high-end hardware, you can escape this by holding the forward key and waiting for the server to lag long enough for you to escape. On lower-end hardware (for example, if I run my client on Intel's integrated graphics rather than my nvidia card), the server remains faster than the client and it is inescapable unless you force close the client.

Server is running with non-default JVM settings `-Xms2G -Xmx5G -d64`
Client is running with default.

**Comment by Lachney** [comment] 2018-11-28 18:36
If the portal looping issue is still happening @NoahJelen @EnderT5 @jotac0 @BabblingFishes Let us know!

Does this happen with the latest version of ![Aether Legacy](https://minecraft.curseforge.com/projects/aether-legacy)? We will further look into portal looping issues in an upcoming patch release for 1.10, 1.11, and 1.12

**Comment by Lachney** [comment] 2018-11-29 23:27
@BabblingFishes Thank you for letting me know.  I will keep this in mind for when we create our patch release.

**Comment by 115kino** [comment] 2019-02-01 00:46
Fixed in the future v1.4.0 release build.

**Closed by 115kino** 2019-02-01 00:46 UTC
Labels: Confirmed Issue
