### ISSUE TITLE
bronze dungeons spawn too rarely

### ISSUE THREAD

**Issue by EdgyWedgy** [Modding-Legacy/Aether-Legacy#222] opened 2017-11-12 22:54 UTC
I'm not sure if I'm incredibly unlucky but it's really hard to find bronze dungeons. The silver and the gold seem to be more common than the bronze. I checked in multiple worlds and it's still the same thing. 
I don't know, I could be extremely unlucky. :/

**Comment by KingPhygieBoo** [comment] 2017-11-12 22:55
Dupe of #153

**Closed by KingPhygieBoo** 2017-11-12 22:55 UTC
