### ISSUE TITLE
[Bug] [19W09a] Trees Generate Strangely, and Leaf Blocks attached to trees degenerate

### ISSUE THREAD

**Issue by ScytheIronclaw** [Modding-Legacy/Aether-Legacy#393] opened 2019-03-07 05:58 UTC
**Aether Legacy Version(s)**
Aether Legacy 19w09a-0.0.2

**Minecraft Version(s) Affected:**
19W09a

**Extra Mod(s):**
fabric-0.2.3.109.jar

**Describe the bug**
All generated trees in Minecraft seem to generate missing a few logs on the top of the trees. The leaves that generate as part of the trees have their distance flags set to 7 regardless of how close the leaves are to the wood log blocks. This causes every tree in the game to have all of their leaves degenerate.

**Expected behavior**
Normal trees with leaves that do not degenerate unless the proper distance away from a log.

**Logs/Crash Logs and Screenshots**
https://pastebin.com/EwRwWzeV

![2019-03-07_00 44 51](https://user-images.githubusercontent.com/20233641/53935317-d75b1c80-4073-11e9-9b34-a24c223a63de.png)

**Additional context**
N/A

**Comment by Indianajaune** [comment] 2019-03-07 08:16
Same issue on mine, probably to extensive use of mixins in the mod.

**Comment by CDAGaming** [comment] 2019-03-09 21:03
Duplicate of https://github.com/Modding-Legacy/Aether-Legacy-Rift/issues/21 :P

Might look into this tonight, just finished some other projects so I have some time 👍

**Comment by CDAGaming** [comment] 2019-03-09 23:44
@ScytheIronclaw This has now been fixed in https://github.com/Modding-Legacy/Aether-Legacy-Rift/commit/fbfe117775f39ea767dec5ed65a529b77713fac7 (Thanks Kino!)

Stay Tuned to the Next Release!

**Comment by Lachney** [comment] 2019-03-10 19:09
You can also download latest builds here if you don't want to wait. :)
https://builds.moddinglegacy.com/job/Aether-Legacy-Fabric/

**Closed** 2019-03-14 21:50 UTC
Labels: Bug, Fabric
