### ISSUE TITLE
STOP TAKING OVER OUR GAME

### ISSUE THREAD

**Issue by Boolyman** [Modding-Legacy/Aether-Legacy#101] opened 2017-03-23 06:34 UTC
You guys are getting really out of line with hijacking parts of our minecraft launcher that have nothing to do with the Aether dimension.

 Fine, you want to put stupid random messages on our loading screen, without asking us, and with no option for us to disable or change them... I ignored that.  But now there is a forced custom Aether Game launch menu when you create a new world... are you serious?  

 We downloaded your mod for the lore of your dimension... stay in your lane, stop hijacking parts of our modpacks that have nothing to do with the Aether dimension.  Im rolling back to a version before this unsolicited menu garbage was added.  

**Edit: Before you guys continue telling me to check the configs, like a help desk employee reading a script... YOU check the configs, and realize that the true/false toggle doesn't actually do ANYTHING.**

**Comment by KingPhygieBoo** [comment] 2017-03-23 07:15
There is a config option to disable the Aether Menu.

**Comment by 115kino** [comment] 2017-03-23 13:19
Boolyman, In the Aether v1.4 changelogs I have noticed that Trivia and Aether menu now have a configuration option to disable/enable it. People requested the Aether menu to come back so I added it back WITH the option to disable it so everyone is happy.

**Comment by jorgeiscool2** [comment] 2017-03-23 13:41
Hey Jorge here!
Boolyman I understand your concern with the Aether Legacy menu which was brought back from the previous version of Aether (Aether 1.2.5) like Kino said there is a config to remove it, but that still doesn't give you the right too tell us what we can't mod here. Remember, why do you think it's called Aether Legacy? That's because we recreated the original Aether mod from 1.2.5 for everyone to experience. Yes the menu and the tips thing on loading screens were there as well. Kino went out of his way to make it so you can disable it with your own pleasure. Also like I stated before about the menu. Your mod pack and other people's mod packs don't change anything on what our goal for this mod was. Feel free to use it in your mod pack yes, but if your really complaining about the menu that you can disable then I don't know what's up with you. You didn't even bother checking the config when you posted this. To be honest I'm surprised you don't act the same way with Aether II the mod that does the same thing with the menu except ours has a bit more features.

**Comment by Senseidragon** [comment] 2017-03-23 20:44
Just a minor point here...  When I create a fresh pack with (for example) just Betweenlands and Aether Legacy installed, I boot up, get the Betweenlands menu, create a singleplayer world, start to enter world (generating terrain) and then I get an Aether Legacy menu.  I checked the configs, and menu is set to false.

If you incorrectly try to do anything at this second menu, you will very likely lock up the game.  If you instead hit ESCAPE, the menu disappears and the world works normally.

So yes, a config option was added to bypass that Aether menu, but in some cases, it certainly doesn't appear to be working as intended.  :)

**Comment by MysticAura** [comment] 2017-03-23 23:50
I disabled it in the config, but it's still enabled.  Don't get me wrong..the menu screen is incredibly well done and I wouldn't care for a personal pack, but I'm making a pack for a streamer and need the default main menu working.

**Comment by 115kino** [comment] 2017-03-24 01:53
I'll do a quick hot fix, it will be out as soon as possible.

**Comment by Boolyman** [comment] 2017-03-24 13:47
Im not reading the wall of text from people telling me to check the configs.  If THEY had checked the configs, they would realize that syntax in the config is broken, and doesnt work.

**Comment by 115kino** [comment] 2017-03-24 15:56
The syntax was inverted. It's fixed in v1.4.1 and will release ASAP.

**Closed by 115kino** 2017-03-24 15:56 UTC
