### ISSUE TITLE
Crash While Exploring Aether

### ISSUE THREAD

**Issue by kreezxil** [Modding-Legacy/Aether-Legacy#353] opened 2018-10-14 12:34 UTC
**Aether Legacy Version(s) Affected**:
1.12.2-v3.2

**Forge version**: 
1.12.2-14.23.5.2770

**Extra Mods**: 
http://paste.ubuntu.com/p/s3tNZBPZY7/

**Issue:**
Aether crashed client side.

**How to reproduce:**
I was flying around the aether looking for good scenery to use in my mod while in creative.

**Crash log:** 
https://pastebin.com/qf0Drikf

**Comment by Lachney** [comment] 2018-11-28 18:20
Aether Legacy Swet Crash - gonna be fixing this soon

**Comment by DemonfangArun** [comment] 2019-01-02 21:46
"me too" goes here

https://paste.dimdev.org/umofusewob.mccrash

**Comment by KingPhygieBoo** [comment] 2019-01-29 03:45
Closing as this is a dupe of #311

**Closed by KingPhygieBoo** 2019-01-29 03:45 UTC
Labels: Confirmed Issue
